---
- name: install nagios
  apt:
    name: nagios3
    state: present
    update_cache: yes
  become: yes

- name: add nagios authentication user and password
  command: "htpasswd -c -b  /etc/nagios3/htpasswd.users {{auth_user}} {{auth_password}}"
  become: yes

- name: give nagios permission for our new user in nagixo cgi.cfg file
  replace:
    dest: /etc/nagios3/cgi.cfg
    regexp: 'nagiosadmin'
    replace: '{{auth_user}}'
    backup: yes
  become: yes

- name: check nagios accessable
  uri:
    method: GET
    url: "http://{{host_private_ip}}/nagios3/"
    force_basic_auth: yes
    user: "{{auth_user}}"
    password: "{{auth_password}}"
    status_code: 200

- name: set up customized configuration
  notify: restart nagios
  copy:
    src: "{{item.src}}"
    dest: "{{nagios_object_dir}}/{{item.dest}}"
    owner: root
    group: root
    mode: 644
  with_items:
    - { src: hosts.cfg, dest: hosts.cfg }
    - { src: hostgroups.cfg, dest: hostgroups.cfg }
    - { src: services.cfg, dest: services.cfg }
    - { src: commands.cfg, dest: additional_commands.cfg }
  become: yes